import numpy as np

# pixel features
GAUSS_DEFAULT_SIGMAS = [1, np.sqrt(2), 2]
GAUSS_DEFAULT_NUM_ORIENTATIONS = 6
ENTROPY_DEFAULT_MIN_NEIGHBORHOOD_RANGE = 2
ENTROPY_DEFAULT_NUM_NEIGHBORHOODS = 3

# training selector
GIST_DEFAULT_GABOR_FREQUENCIES = (.1, .25, .4)
GIST_DEFAULT_GABOR_NUM_ORIENTATIONS = (4, 8, 8)

# utils
TILE_DEFAULT_WIDTH = 512
TILE_DEFAULT_HEIGHT = 512
TILE_DEFAULT_OUTPUT_FILENAME = 'tile_{}-{}.tif'
