import numpy as np

# pixel features
GAUSS_DEFAULT_SIGMAS = [1, np.sqrt(2), 2]
GAUSS_DEFAULT_NUM_ORIENTATIONS = 6
ENTROPY_DEFAULT_MIN_NEIGHBORHOOD_RANGE = 2
ENTROPY_DEFAULT_NUM_NEIGHBORHOODS = 3

# build response
RESPONSE_DEFAULT_TREE_VAL = 0
RESPONSE_DEFAULT_NONTREE_VAL = 0

# classify
ADABOOST_DEFAULT_NUM_ESTIMATORS = 200
REFINE_DEFAULT_SCALE = 10000
REFINE_DEFAULT_BETA = 10

# utils
TILE_DEFAULT_WIDTH = 512
TILE_DEFAULT_HEIGHT = 512
TILE_DEFAULT_OUTPUT_FILENAME = 'tile_{}-{}.tif'
TILE_DEFAULT_FILENAME_PATTERN = '*.tif'
