name: detectree
channels:
  - conda-forge
dependencies:
  - lightgbm=4.5.0
  - pydata-sphinx-theme=0.16.1
  - sphinx=8.1.3
  - sphinx-click=6.0.0
  - sphinx-mdinclude=0.6.2
  - sphinxcontrib-bibtex=2.6.3
